steps:
  # =========================
  # 1. Setup Artifact Registry
  # =========================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - >
        gcloud artifacts repositories describe ${_AR_REPO} --location=${_REGION}
        || gcloud artifacts repositories create ${_AR_REPO} --repository-format=docker --location=${_REGION};
        gcloud auth configure-docker ${_REGION}-docker.pkg.dev --quiet

  # =========================
  # 2. Build Next.js App (Unified)
  # =========================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/chambal-cms'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'frontend'

  # =========================
  # 3. Push Image
  # =========================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/chambal-cms'

  # =========================
  # 4. Deploy to Cloud Run
  # =========================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chambal-cms'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/chambal-cms'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_INSTANCE}'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-env-vars'
      - 'DATABASE_URL=mysql://${_DB_USER}:${_DB_PASSWORD}@localhost/${_DB_NAME}?socket=/cloudsql/${_CLOUD_SQL_INSTANCE}'
      - '--set-secrets'
      - 'AUTH_SECRET=AUTH_SECRET:latest,AUTH_URL=AUTH_URL:latest'

# =========================
# Substitution Variables
# =========================
substitutions:
  _REGION: asia-south2
  _AR_REPO: chambal
  _CLOUD_SQL_INSTANCE: chambal-485109:asia-south2:chambal-db-instance
  _DB_NAME: chambal
  _DB_USER: chambal
  _DB_PASSWORD: ',SigC*P"gX1"Z>IY' # Quoted to handle special chars
  # Note: API_BASE_URL is removed as we are now Server Actions (Internal)

# =========================
# Images to Track
# =========================
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/chambal-cms'

# =========================
# Options
# =========================
options:
  logging: CLOUD_LOGGING_ONLY
#sfgng