steps:
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south2-docker.pkg.dev/$PROJECT_ID/chambal/chambal-backend', './backend']
  
  # Push Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south2-docker.pkg.dev/$PROJECT_ID/chambal/chambal-backend']

  # Build Frontend
  # We pass the API URL as a build argument if needed, but Next.js 'env' in config inlines it.
  # For runtime config, we should rely on client-side fetching or public runtime config (deprecated/limited in app dir).
  # We will assume NEXT_PUBLIC_API_BASE_URL is provided at build time via substitutions.
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}'
      - '-t'
      - 'asia-south2-docker.pkg.dev/$PROJECT_ID/chambal/chambal-frontend'
      - './frontend-legacy'

  # Push Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south2-docker.pkg.dev/$PROJECT_ID/chambal/chambal-frontend']

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chambal-backend'
      - '--image'
      - 'asia-south2-docker.pkg.dev/$PROJECT_ID/chambal/chambal-backend'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_INSTANCE}'
      - '--set-env-vars'
      - 'DEBUG=False,DB_HOST=/cloudsql/${_CLOUD_SQL_INSTANCE},DB_NAME=${_DB_NAME},DB_USER=${_DB_USER},DB_PASSWORD=${_DB_PASSWORD},GS_BUCKET_NAME=${_GS_BUCKET_NAME}'

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chambal-frontend'
      - '--image'
      - 'asia-south2-docker.pkg.dev/$PROJECT_ID/chambal/chambal-frontend'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}'

substitutions:
  _REGION: asia-south2
  _CLOUD_SQL_INSTANCE: "project:region:instance"
  _DB_NAME: "chambal"
  _DB_USER: "chambal"
  _DB_PASSWORD: "changeme"
  _GS_BUCKET_NAME: "chambal-media"
  _NEXT_PUBLIC_API_BASE_URL: "https://api.news.invitevista.com" # Update this to your actual backend URL

images:
  - 'asia-south2-docker.pkg.dev/$PROJECT_ID/chambal/chambal-backend'
  - 'asia-south2-docker.pkg.dev/$PROJECT_ID/chambal/chambal-frontend'
options:
  logging: CLOUD_LOGGING_ONLY
