steps:
  # =========================
  # Build Backend (Django)
  # =========================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/chambal-backend'
      - './backend'

  # Push Backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/chambal-backend'

  # =========================
  # Build Frontend (Next.js)
  # =========================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/chambal-frontend'
      - './frontend-legacy'

  # Push Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/chambal-frontend'

  # =========================
  # Deploy Backend (Cloud Run)
  # =========================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chambal-backend'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/chambal-backend'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_INSTANCE}'
      - '--set-env-vars'
      - >
        DEBUG=False,
        DB_HOST=/cloudsql/${_CLOUD_SQL_INSTANCE},
        DB_NAME=${_DB_NAME},
        DB_USER=${_DB_USER},
        DB_PASSWORD=${_DB_PASSWORD},
        GS_BUCKET_NAME=${_GS_BUCKET_NAME}

  # =========================
  # Deploy Frontend (Cloud Run)
  # =========================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chambal-frontend'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/chambal-frontend'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}'

# =========================
# Substitution Variables
# =========================
substitutions:
  _REGION: asia-south2
  _AR_REPO: chambal
  _CLOUD_SQL_INSTANCE: chambal-485109:asia-south2:chambal-db-instance
  _DB_NAME: chambal
  _DB_USER: chambal
  _DB_PASSWORD: ',SigC*P"gX1"Z>IY'
  _GS_BUCKET_NAME: chambal-sandesh-media-prod
  _NEXT_PUBLIC_API_BASE_URL: https://api.news.invitevista.com

# =========================
# Built Images
# =========================
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/chambal-backend'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/chambal-frontend'

# =========================
# Logging Fix (Required)
# =========================
options:
  logging: CLOUD_LOGGING_ONLY
