steps:
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cms-backend:$SHORT_SHA', '-f', 'backend/Dockerfile', 'backend']
    id: 'build-backend'

  # Build Admin Panel
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cms-admin:$SHORT_SHA', '-f', 'admin/Dockerfile', 'admin']
    id: 'build-admin'

  # Build Website
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cms-website:$SHORT_SHA', '-f', 'website/Dockerfile', 'website']
    id: 'build-website'

  # Push Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cms-backend:$SHORT_SHA']
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push Admin
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cms-admin:$SHORT_SHA']
    id: 'push-admin'
    waitFor: ['build-admin']

  # Push Website
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cms-website:$SHORT_SHA']
    id: 'push-website'
    waitFor: ['build-website']

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cms-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cms-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL},JWT_SECRET=${_JWT_SECRET},JWT_EXPIRES_IN=7d,NODE_ENV=production,CORS_ORIGIN=${_CORS_ORIGIN},MEDIA_UPLOAD_PATH=/tmp/uploads,MEDIA_BASE_URL=${_MEDIA_BASE_URL}'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Deploy Admin to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cms-admin'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cms-admin:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'VITE_API_URL=${_ADMIN_API_URL}'
    id: 'deploy-admin'
    waitFor: ['push-admin']

  # Deploy Website to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cms-website'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cms-website:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_URL=${_WEBSITE_API_URL}'
    id: 'deploy-website'
    waitFor: ['push-website']

images:
  - 'gcr.io/$PROJECT_ID/cms-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/cms-admin:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/cms-website:$SHORT_SHA'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'
