# Generated by Django 4.2.7 on 2026-01-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_remove_category_slug_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Chambal Sandesh', help_text='Site name/title', max_length=200)),
                ('site_tagline', models.CharField(blank=True, help_text='Site tagline or description', max_length=300, null=True)),
                ('site_logo', models.ImageField(blank=True, help_text='Site logo image', null=True, upload_to='settings/')),
                ('site_favicon', models.ImageField(blank=True, help_text='Site favicon', null=True, upload_to='settings/')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_address', models.TextField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('default_seo_title', models.CharField(blank=True, help_text='Default SEO title', max_length=70, null=True)),
                ('default_seo_description', models.TextField(blank=True, help_text='Default SEO description', max_length=160, null=True)),
                ('default_seo_keywords', models.CharField(blank=True, help_text='Default SEO keywords (comma-separated)', max_length=200, null=True)),
                ('posts_per_page', models.PositiveIntegerField(default=20, help_text='Number of posts per page')),
                ('enable_comments', models.BooleanField(default=False, help_text='Enable comments on posts')),
                ('enable_registration', models.BooleanField(default=False, help_text='Allow user registration')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message to show during maintenance', null=True)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics Tracking ID', max_length=50, null=True)),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='Facebook Pixel ID', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
