# Generated by Django 4.2.7 on 2026-01-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='Upload video file', null=True, upload_to='posts/videos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, help_text='Or embed video from YouTube/Vimeo/etc.', null=True),
        ),
    ]
